vmware-labs/webassembly-language-runtimes

.gitignore
libs/sqlite/README.md
libs/sqlite/version-3.39.2/build.sh
libs/sqlite/version-3.39.2/patch.v1.diff
php/README.md
php/patches/7.3.33/build.sh
php/patches/7.3.33/wasmlabs-README.md
php/patches/7.4.32/build.sh
php/patches/7.4.32/patch.v1.diff
php/patches/7.4.32/wasmlabs-README.md

1. This is the initial version of the 7.4.32 patch. We still need to debug why it cannot handle WP
2. Add scripts for reproducible builds.

Php 7.4.32 initial patch with scripts for reproducible build

---

.github/workflows/build-php.yaml
.github/workflows/release-php.yaml
README.md

- In PHP build pipelines, use `.wasm` as the suffix for the artifacts uploaded to the workflow run.
- In PHP release pipelines, enforce the need for tagging with metadata information. By convention and as an example with PHP, `php/7.3.33+20221123-8dfe8b9` would tag the release pipeline, create a GitHub release, produce the required artifacts and upload them to the release.

chore: update pipelines

---

.github/workflows/build-php.yaml
.github/workflows/release-php.yaml
Makefile
README.md
php/Makefile

This target generates a specific PHP CLI targeting wasmedge. This allows for this WebAssembly module to, e.g. perform a `socket` call in order to create a listening socket as opposed to a socket being created by the host, and the file descriptor being forwarded to the WebAssembly module.
It also exports  a `connect` function that resembles `connect(3)`.
The `WASMLABS_RUNTIME` is exposed to the build scripts in order to produce the specified target.
An example of this workflow run: https://github.com/ereslibre/webassembly-language-runtimes/releases/tag/php%2F7.4.32%2B20221223-4e86d34

feature: Add php/wasmedge-php-7.4.32 Makefile target

---

php/php-8.1.11/README.md
php/php-8.1.11/patches/0001-Initial-port-of-the-php-7.4.32-patch-for-php-8.1.11.patch
php/php-8.1.11/patches/0002-feat-Incapacitate-fibers-when-compiling-for-WASI.patch
php/php-8.1.11/wl-build-deps.sh
php/php-8.1.11/wl-build.sh
php/php-8.1.11/wl-tag.sh
php/php-8.1.11/wl-test.sh
php/php-8.2.0/patches/0001-Initial-port-of-the-php-7.4.32-patch-for-php-8.2.11.patch
php/php-8.2.0/patches/0002-feat-Incapacitate-fibers-when-compiling-for-WASI.patch
php/php-8.2.0/patches/0003-fix-Add-more-ifdefs-for-php-8.2.0.patch
php/php-8.2.0/patches/0004-fix-Fix-memory-issues-and-introduce-WASM_WASMEDGE.patch
php/php-8.2.0/patches/0005-feat-Server-sockets-via-with-wasm-runtime-wasmedge.patch
php/php-8.2.0/wl-build-deps.sh
php/php-8.2.0/wl-build.sh
php/php-8.2.0/wl-tag.sh
php/php-8.2.0/wl-test.sh

- Port the existing php 7 patches to php-8.1.11 and php-8.2.0
- Fibers are not supported - attempts to use Fiber code will lead to errors.
- WasmEdge (server-side sockets) are only available for php-8.2.0

Add support for php8

---

Dockerfile.wasi-builder
Makefile.builders
php/Dockerfile
php/Makefile
php/php-7.3.33/patches/0004-Disable-usage-of-mmap-to-fix-correctness-and-stabili.patch
php/php-7.3.33/patches/0005-Remove-build-script-from-patch.patch
php/php-7.3.33/wasmlabs-README.md
php/php-7.4.32/patches/0002-Fix-mmap-issues.-Add-readme.patch
php/php-7.4.32/patches/0003-Remove-files.patch
php/php-7.4.32/wasmlabs-README.md

Note: the branch name is not reflecting the real change, but I don't think it's worth reopening the PR just for that.
Fixes: https://github.com/vmware-labs/webassembly-language-runtimes/issues/23

chore: Bump wasi-sdk

---

libs/uuid/libuuid-1.0.3/wl-build.sh
libs/uuid/wl-env-repo.sh
libs/zlib/v1.2.11/wl-build.sh
libs/zlib/wl-env-repo.sh
python/README.md
python/v3.11.1/wl-build-deps.sh
python/v3.11.1/wl-build.sh
python/v3.11.1/wl-tag.sh
python/wl-env-repo.sh
scripts/wl-hostbuild.sh

This is an initial version that builds python wasm using the CPython build scripts
It leverages the wasm library binaries available in `https://github.com/singlestore-labs/python-wasi/tree/main/docker`
Created issues to fix that subsequently
- https://github.com/vmware-labs/webassembly-language-runtimes/issues/29
- https://github.com/vmware-labs/webassembly-language-runtimes/issues/30
Instructions on how to build can be found in [python/README.md](python/README.md)
Note: this does not include gitactions for releasing of the binary. They will be added subsequently.

feat: Add scripts that generate a python wasm binary

---

Dockerfile.wasi-builder
Dockerfile.wasm-base
Makefile
Makefile.builders
ruby/.dockerignore
ruby/Dockerfile
ruby/Makefile
ruby/README.md
ruby/v3_2_0/wl-build.sh
ruby/v3_2_0/wl-tag.sh
ruby/wl-env-repo.sh

As part of this work, introduce the concept of a wasm-base base image that contains common tooling for handling WebAssembly common artifacts.
This base image contains Binaryen as of now, so that we can run `wasm-opt` on the resulting binaries, for example, to run the Asyncify pass on certain resulting artifacts.

Add Ruby 3.2.0

---

.github/workflows/build-php.yaml
.github/workflows/build-ruby.yaml
.github/workflows/release-php.yaml
.github/workflows/release-ruby.yaml
php/php-7.3.33/wl-build.sh
php/php-7.4.32/wl-build.sh
php/php-8.1.11/wl-build.sh
php/php-8.2.0/wl-build.sh
ruby/v3_2_0/wl-build.sh

Fixes: https://github.com/vmware-labs/webassembly-language-runtimes/issues/12
Besides adding the GH workflows to build and release Ruby, this PR also improves the PHP pipelines so that the Asyncify pass happens on the local developer machine, instead of on a GitHub workflow.

Add Ruby GH workflows

---

Dockerfile.wasi-builder
Dockerfile.wasm-base
Makefile.builders
README.md
libs/sqlite/version-3.39.2/wl-build.sh
php/Dockerfile
php/Makefile
php/php-7.3.33/wl-build.sh
php/php-7.4.32/wl-build.sh
php/php-8.1.11/wl-build.sh
php/php-8.2.0/wl-build.sh
python/Dockerfile
python/Makefile
python/v3.11.1/wl-build.sh
ruby/Dockerfile
ruby/Makefile
ruby/v3_2_0/wl-build.sh

If the envvar `WASMLABS_SKIP_CONFIGURE` is exported, build scripts will skip the configure step.

feature: Allow to skip the configure step

---

Dockerfile.wasm-base

Opening this PR to check whether all tests pass if updating the Ubuntu image.

feat: Updating Docker `wasm-base` image to Ubuntu 22.04 LTS (needed for updating Autotools)

---

Makefile
php/Makefile
php/master/patches/0001-Add-support-for-building-to-the-wasm32-wasi-target.patch
php/master/wl-build-deps.sh
php/master/wl-build.sh
php/master/wl-test.sh

Add the PHP master branch to the list of available Makefile targets. We can add specific automation, cron based for example, so that it can notify us when our patch gets out of sync with the master branch and needs a rebase.

feature: add PHP master with proposed upstream patch

---

.github/workflows/release-python.yaml
Makefile
images/python/Dockerfile
python/v3.11.1/wl-build.sh

- fix the annoying 'Could not find platform independent/dependent libraries' warning
- package the python-wasmedge flavor in the release
- fix building of the python-wasm container

11 python fixes

---

.dockerignore
.github/workflows/build-php-nightly.yaml
.github/workflows/build-php.yaml
.github/workflows/build-python.yaml
.github/workflows/build-ruby.yaml
.github/workflows/build-uuid.yaml
.github/workflows/build-zlib.yaml
.github/workflows/release-php.yaml
.github/workflows/release-python.yaml
.github/workflows/release-ruby.yaml
.github/workflows/release-uuid.yaml
.github/workflows/release-zlib.yaml
Dockerfile.wasi-builder
Dockerfile.wasm-base
Makefile
Makefile.builders
Makefile.helpers
README.md
libs/uuid/Makefile
libs/zlib/Makefile
php/.dockerignore
php/Makefile
python/.dockerignore
python/Makefile
ruby/.dockerignore
ruby/Makefile

- Basic containers have been published here - https://github.com/orgs/vmware-labs/packages?tab=packages&q=wasmlabs
- Simplify Makefiles by extracting common patterns into Makefile.helpers
Rebuilding and re-publishing of the containers is a manual step.
You will need to call the exact Makefile explicitly. e.g.
```
make -f Makefile.builders wasi-builder-19
make -f Makefile.builders push-wasi-builder-19
```
or
```
make -f php/Makefile php-builder
make -f php/Makefile push-php-builder
```

feat: Publish builder containers for faster builds

---

.github/workflows/build-php.yaml
.github/workflows/build-python.yaml
.github/workflows/build-ruby.yaml
.github/workflows/build-uuid.yaml
.github/workflows/build-zlib.yaml

Given other branches than main will need a PR to merge into main, we will run CI workflows on the PR itself, that contains a trigger of its own.

chore: only run actions on the main branch

---

python/Dockerfile
python/v3.11.1/wl-build.sh

We were rebuilding python 3.11 on the host in order to build for wasm
Now this is done as part of the python-builder image
Images have been pushed

chore: Add host python (for building) in python-builder

---

.github/workflows/build-libs-sqlite.yaml
libs/sqlite/v3.41.2/patches/0001-Allow-installation-of-headers-and-pkg-config-files-w.patch
libs/sqlite/v3.41.2/wlr-build.sh
libs/sqlite/v3.41.2/wlr-env-repo.sh
libs/sqlite/v3.41.2/wlr-tag.sh

Add build for sqlite 3.41.2.
- latest sqlite version
- build uses the upstream `--with-wasi-sdk` instead of configuring it manually
Specifically, this is the build check for this version passing - https://github.com/vmware-labs/webassembly-language-runtimes/actions/runs/4553726443/jobs/8030648775?pr=85
Here is a sample release - https://github.com/assambar/webassembly-language-runtimes/releases/tag/libs%2Fsqlite%2F3.41.2%2B20230329-3d86e1b

Sqlite 3.41.2

---

php/php-8.2.0/patches/0017-fix-is_writable-with-stat-bypass.patch

In wasi-libc `stat()`, since there is no user/group concept in Wasm, `st_mode` is initialized to `000`, as well as `st_uid` and `st_gid`. This way, `is_readable()`,  `is_writable()` and `is_executable()` will return `TRUE`.
Two approaches have been discussed:
1. Patch those methods to always return TRUE. This works for many scenarios since most PHP apps will later check (ie: `fopen()`) the concrete operation returns the right value even if the `is_xxxable()` function was previously called.
1. Trial and error. To avoid the above assumption and returning fake values that might be totally wrong, a different approach is to actually try to open/write those resources and return the result.
The latter approach seems more appropriate. The only drawback is a small penalty in performance since the …

fix: Patch for `is_readable()` and `is_writable()` to bypass WASI preview1 limitations with stating files

---

php/php-8.2.0/patches/0018-fix-random_bytes-failing-on-Windows.patch

We are not currently providing a way to get random bytes in __wasi__ mode so it fallbacks to read from "/dev/urandom", which works when the module is running on Unix (and has permissions) but will always fail on Windows, where it does not exist.
The patch provides a way of getting random bytes using getentropy and disables relying on "/dev/urandom" as a fallback.

fix random_bytes failing on Windows

---

.github/workflows/release-php.yaml

Fixed name can be seen here - https://github.com/assambar/webassembly-language-runtimes/releases/tag/php%2F8.2.0%2B20230418-79f102d
From `php-wasmedge.wasm` to `php-8.2.0-wasmedge.wasm`
Note: tried doing it in a better way (similar to what we have with libs), but could not make it workeasily, so just reused the "build-php-cli" which we got from earlier WasmEdge releases. Again, this should be fixed with proper flavors and name decisions taken during the actual build.

fix: Asset name for PHP CLI with wasmedge

---

.github/workflows/build-libs-bzip2.yaml
.github/workflows/release-libs-bzip2.yaml
Makefile
libs/Makefile
libs/bzip2/Makefile
libs/bzip2/README.md
libs/bzip2/v1.0.8/patches/0001-chore-Add-libinstall-to-Makefile.patch
libs/bzip2/v1.0.8/wlr-build.sh
libs/bzip2/v1.0.8/wlr-env-repo.sh
libs/bzip2/v1.0.8/wlr-tag.sh
scripts/build-helpers/wlr_pkg_config.sh

This only builds the library. The accompanying binaries used signals and file ownership, which are not available on WASI.
Here is a sample release - https://github.com/assambar/webassembly-language-runtimes/releases/tag/libs%2Fbzip2%2F1.0.8%2B20230424-ffa3f41
Also, managed to build python with this and test it 
```
wasmtime --mapdir /::$(pwd) bin/python.wasm
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr 24 2023, 11:57:12) [Clang 15.0.7 ] on wasi
Type "help", "copyright", "credits" or "license" for more information.
>>> import bz2
>>> dir(bz2)
['BZ2Compressor', 'BZ2Decompressor', 'BZ2File', '_MODE_CLOSED', '_MODE_READ', '_MODE_WRITE', '__all__', '__author__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_builtin_open', …
```

feat: Add libs/bzip2 to WLR

---

.github/workflows/build-python.yaml
Makefile
images/python/Dockerfile
php/examples/wp-nginx-php-fcgi-mysql/README.md
python/examples/README.md
python/examples/run_all_snippets.sh
python/v3.11.1/wlr-build.sh
python/v3.11.3/wlr-build-deps.sh
python/v3.11.3/wlr-build.sh
python/v3.11.3/wlr-env-repo.sh
python/v3.11.3/wlr-tag.sh

- latest Python version is now 3.11.3 - (https://github.com/vmware-labs/webassembly-language-runtimes/issues/69) We still have the build scripts for 3.11.1, but releases and CI will only work with 3.11.3. Will remove 3.11.1 within the next couple of weeks.
- fixed .pc files for libpython3.11.a (https://github.com/vmware-labs/webassembly-language-runtimes/issues/71)
- fixed misleading Python docs regarding socket support in WasmEdge  (https://github.com/vmware-labs/webassembly-language-runtimes/issues/96)
- fixed docker platform for the new (3.11.3) Python images (https://github.com/vmware-labs/webassembly-language-runtimes/issues/94)
- added bzip2 to the Python build
- fixed container description (removed "WasmEdge" from the standard WASI image) for the new Python images …

Add Python 3.11.3

---

Dockerfile.wasi-builder
Makefile.builders
Makefile.helpers
docs/developers.md
libs/bundle_wlr/Makefile
libs/bzip2/Makefile
libs/icu/Makefile
libs/libjpeg/Makefile
libs/libpng/Makefile
libs/libuuid/Makefile
libs/libxml2/Makefile
libs/oniguruma/Makefile
libs/sqlite/Makefile
libs/wasmedge_sock/Makefile
libs/zlib/Makefile
php/Makefile
php/php-8.1.11/wlr-build.sh
php/php-8.2.0-slim/wlr-build.sh
php/php-8.2.0/wlr-build.sh
python/Makefile
ruby/Makefile

- Simplified usage of wasi-sdk-version 
- Update default wasi-sdk version used for builds.
- Added docs about this process
This is a first of several changes. After republishing libs with the latest wasi-sdk, I will bump dependencies and publish php/python/ruby, etc.

wasi-sdk version to 20

---

libs/wasmedge_sock/.clang-format
libs/wasmedge_sock/README.md
libs/wasmedge_sock/include/netdb.h
libs/wasmedge_sock/netdb.c
libs/wasmedge_sock/wasi_socket_ext.c
libs/wasmedge_sock/wlr-build.sh
php/examples/mysql/run_me.sh
php/v8.2.6/patches/0019-chore-Remove-wasmedge_stubs-and-use-libwasmedge_sock.patch
php/v8.2.6/wlr-build.sh
php/v8.2.6/wlr-info.json

- Updated libs/wasmedge_sock with latest fixes from the PHP custom stubs
- Modified the PHP build to use libs/wasmedge_sock
This is an intermediary step in my effort to add WasmEdge socket support to our CPython build.
Note: Did not update the wasmedge_sock version as it was never used or published before.

Use libwasmedge_sock in PHP instead of custom stubs

---

Makefile
python/v3.12.0/wlr-build.sh

Add the static hashlib module to the bundled libpython. Without this using libpython will fail with undefined symbols.

fix: libpython and targets for python docker images

---

python/tools/wlr-libpy/Cargo.lock
python/tools/wlr-libpy/Cargo.toml
python/tools/wlr-libpy/README.md
python/tools/wlr-libpy/src/bld_cfg.rs

This is waiting for `https://github.com/PyO3/pyo3/issues/3645` before I can update the respective example in [`python/examples/embedding/wasi-py-rs-pyo3`](https://github.com/vmware-labs/webassembly-language-runtimes/tree/main/python/examples/embedding/wasi-py-rs-pyo3).
I tested it with a locally modified pyo3 (that has the abi3-py312 feature) and it works as expected.

chore: Add libpython3.12 support in wlr-libpy
